[package]
name = "setjmp"
version = "0.1.0"
authors = ["Jeff Davis <jeff@j-davis.com>"]
edition = "2018"
license = "PostgreSQL OR MIT"
description = "setjmp / longjmp support"
repository = "https://github.com/jeff-davis/setjmp.rs"
documentation = "https://docs.rs/setjmp"
